## Chaper 1 - Getting & Knowing Your Data

In [1]:
import pandas as pd

In [5]:
order_details = pd.read_csv('data.tsv.txt',sep='\t' )
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 1.1 Perform Initial Analysis Data

In [6]:
order_details.shape

(4622, 5)

In [7]:
order_details.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [8]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [9]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [10]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

## 1.2 Find out the Items Sold in the Restaurent

In [11]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [13]:
print(order_details['item_name'].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## 1.3 Give me Top 5 Selling Items

In [19]:
order_details.groupby(by='item_name')["quantity"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

## 1.3.1 Give me the list of Least 5 Selling Items

In [26]:
order_details.groupby(by='item_name')["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

## Chapter 2 - Data Cleaning

In [36]:
order_details['item_price'] = order_details['item_price'].str.replace("$","").astype(float) #Chain of Methods

In [37]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [38]:
order_details.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [39]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

### Task 1 - Top 5 Selling Item individual Revenue it made

In [61]:
order_details.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           7342.73
Chicken Burrito        5575.82
Steak Burrito          3851.43
Steak Bowl             2260.19
Chips and Guacamole    2201.04
Name: item_price, dtype: float64

### Task 2 - Total Revenue of the Top 5 Items Sold

In [67]:
Total_Revenue_of_Top_5=order_details.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head().sum()
print(Total_Revenue_of_Top_5)

21231.21

### Task 3 - Total Revenue Sold Items

In [73]:
Total_revenue_of_sold_items=order_details["item_price"].sum()
print(Total_revenue_of_sold_items)

34500.16

### Task 4 - Total Revenue of the Least 5 Items Sold

In [79]:
Least_5_items_total_revenue= order_details.groupby(by='item_name')['item_price'].sum().sort_values().head().sum()
print(Least_5_items_total_revenue)

50.08

## Chapter 3 - Pandas Data Structure

In [81]:
pd.Series(data=[1,2])

0    1
1    2
dtype: int64

In [85]:
pd.DataFrame(data= {"Names" : ["Siva","Naveen","Ribash","Mani"],
                    "Maths" : [75,72,70,80],
                    "Science" : [83,82,80,90]})

    Names  Maths  Science
0    Siva     75       83
1  Naveen     72       82
2  Ribash     70       80
3    Mani     80       90

### Task 1 - Create Meaningful Series

In [89]:
pd.Series(data=[91,79,75,93,98],index=["Tamil","English","Maths","Science","Social"],name= "This is Siva 10th Mark" )

Tamil      91
English    79
Maths      75
Science    93
Social     98
Name: This is Siva 10th Mark, dtype: int64

### Task 2 - Create Meaningful Dataset using pandas DataFrame with Dictionary

In [94]:
Marks=pd.DataFrame(data={"STANDARD" : ["SSLC","HSC-I","HSC-II"],
                  "TOTAL_MARKS" : [436,427,463]})
Marks

  STANDARD  TOTAL_MARKS
0     SSLC          436
1    HSC-I          427
2   HSC-II          463

## Chapter 4 - Filtering, Selection & Sorting

In [98]:
Euro_2012_data = pd.read_csv('Euro_2012_stats_TEAM.csv')
Euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [100]:
Euro_2012_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [122]:
Filter_euro_data=Euro_2012_data[['Team','Goals','Yellow Cards', 'Red Cards']]
Filter_euro_data

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [129]:
Filter_euro_data.sort_values(by='Yellow Cards', ascending=False)

                   Team  Goals  Yellow Cards  Red Cards
7                 Italy      6            16          0
10             Portugal      6            12          0
13                Spain     12            11          0
0               Croatia      4             9          0
6                Greece      5             9          1
14               Sweden      5             7          0
9                Poland      2             7          1
1        Czech Republic      4             7          0
12               Russia      5             6          0
11  Republic of Ireland      1             6          1
4                France      3             6          0
3               England      5             5          0
8           Netherlands      2             5          0
15              Ukraine      2             5          0
5               Germany     10             4          0
2               Denmark      4             4          0

### Task 1 - Top 5 Yellow Cards Team

In [132]:
Filter_euro_data.sort_values(by='Yellow Cards',ascending=False).head()

        Team  Goals  Yellow Cards  Red Cards
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0
0    Croatia      4             9          0
6     Greece      5             9          1

### Task 2 - Red Cards Team

In [134]:
Filter_euro_data[Filter_euro_data['Red Cards'] == 1]

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

### Task 3 - More than 8 Yellow Cards Team

In [135]:
Filter_euro_data[Filter_euro_data['Yellow Cards'] >= 8]

        Team  Goals  Yellow Cards  Red Cards
0    Croatia      4             9          0
6     Greece      5             9          1
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0

### Task 4 - Total Goals

In [146]:
Total_Goals = Filter_euro_data['Goals'].sum()
print("Total_Goals:",Total_Goals)

Total_Goals: 76

### Task 5 - Below 5 Yellow Cards Team

In [149]:
Least_Yellow_Cards_Teams = Filter_euro_data[Filter_euro_data["Yellow Cards"] < 5]
Least_Yellow_Cards_Teams

      Team  Goals  Yellow Cards  Red Cards
2  Denmark      4             4          0
5  Germany     10             4          0

### Task 6 - Zero Red Cards Teams

In [151]:
Filter_euro_data[Filter_euro_data['Red Cards'] == 0]

              Team  Goals  Yellow Cards  Red Cards
0          Croatia      4             9          0
1   Czech Republic      4             7          0
2          Denmark      4             4          0
3          England      5             5          0
4           France      3             6          0
5          Germany     10             4          0
7            Italy      6            16          0
8      Netherlands      2             5          0
10        Portugal      6            12          0
12          Russia      5             6          0
13           Spain     12            11          0
14          Sweden      5             7          0
15         Ukraine      2             5          0

## Chapter 5 - How to Deal with Missing Data

In [4]:
import pandas as pd

In [8]:
employee_data = pd.read_csv('employee_data.csv')
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

# Level 1 of Data Cleaning

### I'll call my client and get right data from him - Great!!

Incase client is asking to perform the data cleaning operatins

#### Step 1 - Remove Duplicates

In [9]:
employee_data_updated = employee_data.drop_duplicates()
employee_data_updated

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

### Step 2 - Find out the Null entries

In [10]:
employee_data_updated.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [21]:
employee_data_updated.dropna()
employee_data_updated

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [22]:
employee_data_updated.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

### Step 3 - Record in  a Documents

client gave totally 7 observations out of 3 observations are removed because of duplicates & null entries

### Step 4 - Get Approval

send this to my client and get approval to proceed for model building or training

In [23]:
employee_data_updated.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

# Level 2 of Data Cleaning

In [24]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [85]:
updated_emp_data=pd.read_excel("employee_data.xlsx",sheet_name = "More_employee_Data" )
updated_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathiew   NaN    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech      NaN 2020-11-12
8       Kuppusamy  28.0        Ops      NaN 2021-05-21
9           Ajesh  28.0    Support      NaN 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-11-12
11        Mathiew   NaN    Support  58000.0 2025-01-15
12  Jagadheeswari  28.0    IT Tech      NaN        NaT
13           Mani  28.0        Ops      NaN 2021-05-21

## Step 1 - Drop duplicates

In [86]:
updated_emp_data.drop_duplicates(inplace=True)

In [87]:
updated_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathiew   NaN    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech      NaN 2020-11-12
8       Kuppusamy  28.0        Ops      NaN 2021-05-21
9           Ajesh  28.0    Support      NaN 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech      NaN        NaT
13           Mani  28.0        Ops      NaN 2021-05-21

## Step 2 - Identify Null Entries

In [73]:
updated_emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     1
dtype: int64

## Step 3 - Go for best Imputation

In [8]:
updated_emp_data['Department'].unique()

array(['Ops', 'IT Tech', 'Support'], dtype=object)

In [90]:
updated_emp_data[updated_emp_data['Department'] == 'Support']

      Name   Age Department   Salary  Join_Date
2  Mathiew   NaN    Support  58000.0 2025-01-15
4    Kevin  28.0    Support  61000.0 2024-07-30
5    Navin  35.0    Support  72000.0 2023-08-19
9    Ajesh  28.0    Support      NaN 2024-07-30

In [88]:
ops=updated_emp_data[updated_emp_data['Department'] == 'Ops']
ops

         Name   Age Department   Salary  Join_Date
0      Rajesh  29.0        Ops  60000.0 2023-05-21
3     Gilbert  29.0        Ops  60000.0 2021-05-21
8   Kuppusamy  28.0        Ops      NaN 2021-05-21
13       Mani  28.0        Ops      NaN 2021-05-21

In [89]:
updated_emp_data[updated_emp_data['Department'] == 'IT Tech']

             Name   Age Department   Salary  Join_Date
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech      NaN 2020-11-12
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech      NaN        NaT

### Task 1 - Impute relevant values in salary column in NaN based on Department

In [114]:
updated_emp_data.loc[(updated_emp_data['Department'] == 'Support') & (updated_emp_data['Salary'].isna()),'Salary'
] = 60000.0
updated_emp_data.loc[updated_emp_data['Name'] == 'Ajesh']

         Name   Age Department   Salary  Join_Date
0      Rajesh  29.0        Ops  60000.0 2023-05-21
3     Gilbert  29.0        Ops  60000.0 2021-05-21
8   Kuppusamy  28.0        Ops      NaN 2021-05-21
13       Mani  28.0        Ops      NaN 2021-05-21

In [117]:
updated_emp_data.loc[(updated_emp_data['Department'] == 'Ops') & (updated_emp_data['Salary'].isna()),'Salary'
] = 60000.0
updated_emp_data.loc[updated_emp_data['Name'] == ['Kuppusamy','Mani']]

ValueError: ('Lengths must match to compare', (13,), (2,))

In [118]:
updated_emp_data[updated_emp_data['Department'] == 'Ops']

         Name   Age Department   Salary  Join_Date
0      Rajesh  29.0        Ops  60000.0 2023-05-21
3     Gilbert  29.0        Ops  60000.0 2021-05-21
8   Kuppusamy  28.0        Ops  60000.0 2021-05-21
13       Mani  28.0        Ops  60000.0 2021-05-21

In [119]:
updated_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathiew   NaN    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech      NaN 2020-11-12
8       Kuppusamy  28.0        Ops  60000.0 2021-05-21
9           Ajesh  28.0    Support  60000.0 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech      NaN        NaT
13           Mani  28.0        Ops  60000.0 2021-05-21

In [120]:
updated_emp_data[updated_emp_data['Department'] == 'IT Tech']

             Name   Age Department   Salary  Join_Date
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech      NaN 2020-11-12
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech      NaN        NaT

In [121]:
updated_emp_data.loc[(updated_emp_data['Department'] == 'IT Tech') & (updated_emp_data['Salary'].isna()),'Salary'
] = [62000.0,59000.0]
updated_emp_data.loc[updated_emp_data['Name'] == ['Roshan','Jagadheeswari']]

ValueError: ('Lengths must match to compare', (13,), (2,))

In [122]:
updated_emp_data[updated_emp_data['Department'] == 'IT Tech']

             Name   Age Department   Salary  Join_Date
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech  62000.0 2020-11-12
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech  59000.0        NaT

In [123]:
updated_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathiew   NaN    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech  62000.0 2020-11-12
8       Kuppusamy  28.0        Ops  60000.0 2021-05-21
9           Ajesh  28.0    Support  60000.0 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech  59000.0        NaT
13           Mani  28.0        Ops  60000.0 2021-05-21

### Task 2 - Impute Mathiew age is 27

In [131]:
updated_emp_data.loc[updated_emp_data['Name'] == 'Mathiew', 'Age'] = 27
updated_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathiew  27.0    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-09-10
7          Roshan  31.0    IT Tech  62000.0 2020-11-12
8       Kuppusamy  28.0        Ops  60000.0 2021-05-21
9           Ajesh  28.0    Support  60000.0 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheeswari  28.0    IT Tech  59000.0        NaT
13           Mani  28.0        Ops  60000.0 2021-05-21