### 1. Write a program to take a name and age from the user and print a greeting message.

In [1]:
user_name=input("Enter Your Name:")
user_age=int(input("Enter Your Age:"))

print(f"Your Name is {user_name} and Your Age is {user_age} Welcome Aboard!!! in ProITBridge")

Enter Your Name: Sivanantham S
Enter Your Age: 24

Your Name is Sivanantham S and Your Age is 24 Welcome Aboard!!! in ProITBridge

### 2. Create a list of numbers and print only even numbers using for loop

In [5]:
random_numbers=range(1,21)
even_numbers=[]
for i in random_numbers:
    if i%2==0:
        even_numbers.append(i)
print("Even Numbers:",even_numbers)

Even Numbers: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

### 3.Write a program that handles division by zero using try-except

In [9]:
First_num=int(input("Enter Your 1st Number:"))
Second_num=int(input("Enter Your 2nd Number:"))

try:
    Divide=First_num/Second_num
    print(Divide)
except ZeroDivisionError:
    print("Invalid Input. Enter Other Than 0")
finally:
    print("Completed")

Enter Your 1st Number: 5
Enter Your 2nd Number: 0

Invalid Input. Enter Other Than 0
Completed

### 4. Given a string, count how many vowels it has.

In [26]:
user_input=input("Your Name:")
count=0
for i in user_input.lower():
    if i in "aeiou":
        count +=1
print(count)

Your Name: Sivanantham

4

### 5. reverse a list without using built-in functions.

In [48]:
user_input=[1,2,3,4,5]
output=[]
for i in user_input:
    output.append(user_input[-1] - i+1)
print(output)

[5, 4, 3, 2, 1]

In [55]:
original_list=[1,2,3,4,5]
reverse_list=[]
i=len(original_list)
while i>0:
    reverse_list.append(i)
    i-=1
print(reverse_list)

[5, 4, 3, 2, 1]

### 6. Create a dict with at least 5 key-value pairs and print them

In [75]:
import pandas as pd
IPL = pd.DataFrame(data={"First_Name" : ["MS","Rohit","Ravindra", "Virat", "Shreyas"], 
                        "Last_Name" : ["Dhoni","Sharma","Jadeja","Kohli","Iyer"],
                        "Team" : ["CSK","MI","RR","RCB","PBKS"],
                        "Home" : ["Pune","Gujarat","Rajasthan","Bangalore","Punjab"],
                        "Champions" : [5,5,1,1,0] } )

IPL

  First_Name Last_Name  Team       Home  Champions
0         MS     Dhoni   CSK       Pune          5
1      Rohit    Sharma    MI    Gujarat          5
2   Ravindra    Jadeja    RR  Rajasthan          1
3      Virat     Kohli   RCB  Bangalore          1
4    Shreyas      Iyer  PBKS     Punjab          0

In [78]:
IPL.to_csv(path_or_buf = "IPL.csv")

### 7. Write a pandas code to read a CSV and print the top 5 rows

In [76]:
pd.read_csv("employee_data.csv").head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

### 8. Craete a DataFrame from a Python Dict

In [79]:
import pandas as pd
IPL = pd.DataFrame(data={"First_Name" : ["MS","Rohit","Ravindra", "Virat", "Shreyas"], 
                        "Last_Name" : ["Dhoni","Sharma","Jadeja","Kohli","Iyer"],
                        "Team" : ["CSK","MI","RR","RCB","PBKS"],
                        "Home" : ["Pune","Gujarat","Rajasthan","Bangalore","Punjab"],
                        "Champions" : [5,5,1,1,0] } )

In [83]:
pd.read_csv("IPL.csv", index_col=0)

  First_Name Last_Name  Team       Home  Champions
0         MS     Dhoni   CSK       Pune          5
1      Rohit    Sharma    MI    Gujarat          5
2   Ravindra    Jadeja    RR  Rajasthan          1
3      Virat     Kohli   RCB  Bangalore          1
4    Shreyas      Iyer  PBKS     Punjab          0

### 9. Replace al Missing values in a DataFrame with the column's mean

In [86]:
employee_data =pd.read_csv("employee_data.csv")
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [87]:
employee_data["Salary"].mean()

np.float64(62500.0)

In [90]:
employee_data["Salary"].fillna(value=employee_data["Salary"].mean(), inplace=True)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9940\2194653261.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employee_data["Salary"].fillna(value=employee_data["Salary"].mean(), inplace=True)

In [91]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

### 10. Filter rows in a DataFrame where the "Age" column greater than 30

In [92]:
employee_data["Age"]>=30

0    False
1     True
2    False
3    False
4    False
5     True
6     True
7     True
Name: Age, dtype: bool

In [94]:
employee_data[employee_data["Age"]>=30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech  62500.0  12-11-2020